export { default as Contact } from "./contact/Contact"
export { default as Contacts } from "./contact/Contacts"
export { default as Navbar } from "./Navbar"
export { default as SearchContact } from "./contact/SearchContact"
export { default as Spinner } from "./Spinner"
export { default as AddContact } from "./contact/AddContact"
export { default as EditContact } from "./contact/EditContact"
export { default as ViewContact } from "./contact/ViewContact"
